### ISSUE TITLE
Bug: game timer

### ISSUE THREAD

**Issue by VatsKan** [fac19/week10-gv#18]
after the game has ended, if we click on the home button or the start new game button,  the setTimeout does not reset.... not sure why it doesn't reset as we update the endGame state to false.

(however could potentially try to implement the timer thing in a state using setInteval instead...but this sounds more complicated)

**Comment by eliascodes** [comment]
This is because you've put a naked `setTimeout` in your component.

https://github.com/fac19/week10-gv/blob/307930b83012ed4985dccfd772280ef4045ea00a/src/components/Game.js#L9-L11

This should be inside a `useEffect` hook, otherwise it will run on every render. Also try to clear your timeouts when the component unmounts using the cleanup feature of `useEffect`: https://reactjs.org/docs/hooks-effect.html#effects-with-cleanup
